#!/bin/bash
function powermenu {
    options="ﰸ Cancel\n襤 Shutdown\nﰇ Restart\n鈴 Sleep\n Lock"
    selected=$(echo -e $options | dmenu -m 0 -c -l 10)
    if [[ $selected = "Shutdown" ]]; then
        loginctl poweroff
    elif [[ $selected = "Restart" ]]; then
        loginctl reboot
    elif [[ $selected = "Sleep" ]]; then
        loginctl hibernate
    elif [[ $selected = "Lock" ]]; then
        slock
    elif [[ $selected = "Cancel" ]]; then
        return
    fi
}

powermenu
